---
- name: Install monitoring tools
  hosts: all
  tasks:
    - name: Install Elasticsearch
      include_role:
        name: elk

    - name: Install Logstash
      include_role:
        name: logstash
 
    - name: Install Kibana
      include_role:
        name: kibana
